# Generated by Django 4.1.3 on 2023-12-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('tipe', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('episode', models.IntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime_images/')),
                ('description', models.TextField()),
                ('produser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.produser')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.studio')),
            ],
        ),
    ]
